# Generated by Django 4.1.5 on 2023-01-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='women',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='women',
            name='time_update',
        ),
    ]
